version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: srivari
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - .dbdata:/var/lib/postgresql
